language: Swift
osx_image: xcode10.0
xcode_project: Robots.xcodeproj # path to your xcodeproj folder
xcode_scheme: Robots

before_install:
  - make init

script:
  - set -o pipefail
  - xcodebuild test -workspace Robots.xcworkspace -scheme Robots -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -enableCodeCoverage YES -destination 'platform=iOS Simulator,name=iPhone 8,OS=12.0' | xcpretty -c 
  
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'Robots'
